#!/bin/sh

builddir=$HOME/blog/dst
homedir=$HOME/blog/src
feeddir=$homedir/feed.xml
temp=$homedir/temp.md
indexdir=$homedir/blogindex.html
blogsdir=~/blog/src/blog/

posts=$(grep -m2 'Date:' ~/blog/src/blog/* | sort -k3M -k3r | cut -d'.' -f1 |  cut -d\/ -f6)
posts_recents=$(grep -m2 'Date:' ~/blog/src/blog/* | sort -k3M -k3r | cut -d'.' -f1 | cut -d\/ -f6 | head -n3)

# generate/update blog entries in blogindex.html
echo "<h1>Articles</h1>" > $indexdir
for post in ${posts}; do
	title=$(grep -m1 '#' $blogsdir/$post.md | cut -c 3-)
        datt=$(grep -m2 'Date' $blogsdir/$post.md | awk '{print $2, $3}')

	echo "<a href="blog/${post}.html">$title</a>" >> $indexdir
	echo "<p class="date">$datt</p><br>" >> $indexdir
done
echo "Done generate"

# updates "recent articles" list of blog entries in the index.md
echo "# Recent Articles" > $temp
for post in ${posts_recents}; do
	title=$(grep -m1 '#' $blogsdir/$post.md | cut -c 3-)
	datt=$(grep -m2 'Date' $blogsdir/$post.md | awk '{print $2, $3}')

	echo " " >> $temp
	echo "- [$title](/blog/${post}.html)" >> $temp
	echo " " >> $temp
	echo "$datt" >> $temp 
	echo " " >> $temp
done

# Remove temp file
cat $homedir/main.md $temp > $homedir/index.md
#rm $temp
echo "Done generate feed"

# generate/update rss feed
echo "<?xml version='1.0' encoding='utf-8'?>" > $feeddir
echo "<rss version='2.0'>" >> $feeddir
echo "<channel>" >> $feeddir
echo "<title>https://peterdiggerstudio.com</title>" >> $feeddir
echo "<description>welcome to my room</description>" >> $feeddir
echo "<link>https://peterdiggerstudio.com</link>" >> $feeddir
for post in ${posts}; do
	title=$(grep -m1 '#' $blogsdir/$post.md | cut -c 3-)
	datt=$(grep -m2 'Date' $blogsdir/$post.md | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}')
	datttemp=$( echo "$datt" |sed 's/,/ /g')
	rssdatt=$(date -R --date="$datttemp")
	echo "<item>" >> $feeddir
	echo "<guid>https://peterdiggerstudio.com/blog/$post.html</guid>" >> $feeddir
	echo "<link>https://peterdiggerstudio.com/blog/$post.html</link>" >> $feeddir
	echo "<pubDate>$rssdatt</pubDate>" >> $feeddir
	echo "<title>$title</title>" >> $feeddir
	#echo "<description>$desc</description>" >> $feeddir
	echo "</item>" >> $feeddir
done
echo "</channel>" >> $feeddir
echo "</rss>" >> $feeddir

# ssg6 rebuild static pages
rm $builddir/.files
ssg6 $homedir $builddir "peter" "https://peterdiggerstudio.com"

# rsync to hosting server
